UWM-RAR: Setting the max-width of the logo to 177px
uwmweb/uwmcms pull request #1879
Opened 2020-10-08 15:35 UTC by smitahantzios

2020-10-08 15:52 UTC, blaquehat requested changes
Added suggested changes to both files.

2020-10-08 15:52 UTC, blaquehat commented on docroot/themes/custom/rar/templates/block/block--rar-uwmed-block.html.twig
> +      <span class="footer-logo">
I suggest undo this change. The included SVG file has an ID set.
![image](https://user-images.githubusercontent.com/9200019/95482542-1da8e980-0943-11eb-802e-604daf1e26e8.png)

2020-10-08 15:52 UTC, blaquehat commented on docroot/themes/custom/rar/src/css/components.css
> +.footer-logo svg {
Change this to `#uw-med-logo`. If you want to be more specific you can use `*[data-block-name="uwmed-block"] #uw-med-logo`

2020-10-08 17:01 UTC, smitahantzios commented on docroot/themes/custom/rar/templates/block/block--rar-uwmed-block.html.twig
> +      <span class="footer-logo">
I just realized, since the SVG is implemented as a TWIG template, there would be a conflict if the template in include more than once on the rendered page. I did a quick search in the code and did not find this template being included more than once, however, do you see a possibility of this happening? Hence, using "class" instead of id is something I would prefer. 

Also, I've made use of the BEM Syntax for the class "footer-logo". This negates the need for adding block-level parent  CSS classes for specificity. I do try to avoid using block-level CSS classes as much as possible.

2020-10-08 17:23 UTC, blaquehat commented on docroot/themes/custom/rar/templates/block/block--rar-uwmed-block.html.twig
> +      <span class="footer-logo">
Using `*[data-block-name="uwmed-block"] #uw-med-logo` narrows it down to the Block and the SVG. 

I do see your point on the class and the use of BEM syntax. In this case, if the block is used somewhere other than the Footer region... it will not correctly represent its use. Another argument can be made if the Footer had 2 logos applied, how to differentiate between them. 

If you want to use the `footer-logo` class, I suggest you make sure the template is aware that it's in the footer region then apply that class (I believe there might be an example in the template).

2020-10-08 18:22 UTC, smitahantzios commented on docroot/themes/custom/rar/templates/block/block--rar-uwmed-block.html.twig
> +      <span class="footer-logo">
Following is what I had in mind:
* Remove the "id" attribute from SVG
* Update the class of the immediate parent of the SVG to **logo--size-md**. 

This takes care of 
* Multiple instances of the logo added anywhere on the page, not just the footer. As long as they all want to have the width of 177px, this class "logo--size-md" can be used.

2020-10-08 18:54 UTC, smitahantzios commented on docroot/themes/custom/rar/templates/block/block--rar-uwmed-block.html.twig
> +      <span class="footer-logo">
The below screenshot shows the styling for this logo that currently is present in the code. However, it became outdated because of the changes to the Drupal configuration.

![image](https://user-images.githubusercontent.com/11652557/95501154-dd169380-0975-11eb-90d9-193a59d66f4b.png)

2020-10-08 20:22 UTC, blaquehat commented on docroot/themes/custom/rar/templates/block/block--rar-uwmed-block.html.twig
> -      <span class="footer-logo">
@smitahantzios, is the class name too generic?

2020-10-08 21:43 UTC, smitahantzios commented on docroot/themes/custom/rar/templates/block/block--rar-uwmed-block.html.twig
> -      <span class="footer-logo">
This class is changed to "logo--size-md"

2020-10-09 12:17 UTC, smitahantzios commented on docroot/themes/custom/rar/templates/block/block--rar-uwmed-block.html.twig
> -      <span class="footer-logo">
The file you looking at is outdated so "footer-logo" doesnt exist

2020-10-09 16:37 UTC, theneonlobster approved these changes

2020-10-11 22:07 UTC, merged