UWM-RAR: Editor interface updates
uwmweb/uwmcms pull request #1932
Opened 2020-10-27 23:25 UTC by sodacrackers

UWM-RAR: Content updates to the RaR theme readme.md; grammar updates. Setting a min-height on body content, for layout builder form confirmation steps.

2020-10-29 15:40 UTC, blaquehat requested changes

2020-10-29 15:40 UTC, blaquehat commented on docroot/themes/custom/rar/readme.md
> +Go to the theme directory (*/docroot/themes/custom/rar*), run `npm install` to download the dependencies above and project packages. After the npmm install, you can run `npm run build:dev` to compile
Small spelling mistake `npmm` should be `npm`.

2020-10-29 15:40 UTC, blaquehat commented on docroot/themes/custom/rar/src/css/base.css
> +  min-height: 500px;
@sodacrackers, Is this meant for all breakpoints or a specific one?

2020-10-29 21:41 UTC, sodacrackers commented on docroot/themes/custom/rar/readme.md
> +Go to the theme directory (*/docroot/themes/custom/rar*), run `npm install` to download the dependencies above and project packages. After the npmm install, you can run `npm run build:dev` to compile
Typo fixed

2020-10-29 21:41 UTC, sodacrackers commented on docroot/themes/custom/rar/src/css/base.css
> +  min-height: 500px;
All breakpoints; it seemed a reasonable safety since we do not have UX spec.

2020-11-03 15:08 UTC, blaquehat commented
Closing due to improvements in https://github.com/uwmweb/uwmcms/pull/1944

2020-11-03 15:08 UTC, closed without merging