Features/rar category icons 539871084
uwmweb/uwmcms pull request #1936
Opened 2020-10-30 18:36 UTC by sodacrackers

Addresses recursive rendering error on RAR pages; addresses loading of category field reference to SVG media item. 

- Adds theme settings for uploading category icon (Well, Mind, Life...) SVG files
- Attaches SVGs to the terms on load 
- Caches loading of the SVG markup
- Provides matching content in the current Twig files

2020-11-02 17:20 UTC, theneonlobster requested changes

2020-11-02 17:20 UTC, theneonlobster commented on docroot/sites/rar/modules/rar_category/rar_category.module
> +      // 'icon' => $category->getRenderableIcon(),
Can we delete the code for getRenderableIcon and begin reducing the complexity of this module?

2020-11-04 00:20 UTC, sodacrackers commented on docroot/sites/rar/modules/rar_category/rar_category.module
> +      // 'icon' => $category->getRenderableIcon(),
Makes sense and most deprecated code has been removed.

2020-11-10 17:11 UTC, theneonlobster approved these changes
Looks great!

2020-11-10 17:29 UTC, merged